### ISSUE TITLE
Unbranding obeesdoo

### ISSUE THREAD

**Issue by robinkeunen** [beescoop/Obeesdoo#138]
Yo,

Now that this repo is used outside the beescoop (5+ supermarket), would it be wise to rename the module names to remove the mentions to the BEES coop? It'd be a good first step to include new developers.

What do you think? What would the replacement be?

**Comment by mclaeysb** [comment]
`OCA/vertical-cooperative-supermarket/cooperative_supermarket_shift` etc?

**Comment by robinkeunen** [comment]
or shorter but that won't be for this version...
