### ISSUE TITLE
Beescard in barcode format in website portal

### ISSUE THREAD

**Issue by Patrickkappert** [beescoop/Obeesdoo#210]
Is it posible to add the Beescard in the website portal for the custumors in a barcode format to easily scan at the cash register?

**Comment by robinkeunen** [comment]
If I understand correctly, you're not using Odoo POS? Because, from the POS, you can scan the user card.

Can you tell me for which supermarket / grocery store you're looking at this code? :-)

All the best.

**Comment by Patrickkappert** [comment]
The idea is not to print any card but that the users have their card at the website portal so it can be scanned from mobile phone at the pos

**Comment by Yo-Be** [comment]
Dont know if it’s what Patrick wants, but it is also useful to have it in the personal space /my/home  in order to use it in a card-wallet app (such as Loyalty card keychain) on smartphone. 
I added it for us (just numbers, not barcode) but maybe there is a widget?

**Comment by Patrickkappert** [comment]
Exactly Yo-be. And thanks, I did not know the loyalty card keychain. If you say I implemented it for us, what does the us refer to? I dont see any repositori. 

I changed the views and  also added the barcode and took out the bank Account information. (SupercoopManresa/vertical-cooperative)

And Robin, us is a cooperative supermarket in Manresa (Catalunya) with 700 members that wants to open in march. https://supercoopmanresa.cat/
We use Obeesdoo via Coopdevs but try to implement ourselves.

Yo-be: did you implement more changes of the views at the website portal?

greetings

**Comment by Yo-Be** [comment]
We are on a mutualized cloud solution (managed by Robin). I only use the HTML/CSS edition function.
I "dirty" added (just found how to add an img of the barcode)
```
<b>Code barre : </b> <t t-esc="user_id.partner_id.barcode" /><br/>
<img t-if="user_id.partner_id.barcode" t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' %('EAN13',user_id.partner_id.barcode,200,25)" ></img>

```
in Portal Layout, inside the `<div class="o_portal_my_details">`

**Comment by Patrickkappert** [comment]
https://user-images.githubusercontent.com/24271175/105333461-0b8f4600-5bd6-11eb-8e84-64076de06ead.png

Now only find out how the tickets from the POS are at the portar (like the bills of the orders)

**Comment by robinkeunen** [comment]
Welcome onboard then! 

Be careful that when modifying directly through the website, you might break future updates on these templates. The best way to do this is by submitting a PR we can integrate in the code, it's usually useful for others as well.

We're open to share on how we deploy our solutions if you need :-)

**Comment by Patrickkappert** [comment]
I put this 

  <p t-if="coop.barcode">
                    <label>Barcode:</label>
                    <t t-esc="coop.barcode"/>
                     <img t-if="coop.barcode" t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' %('EAN13',coop.barcode,200,25)" ></img>
    at easy_my_coop_website_portal_templates.xml

but I understand that I can't put a PR because I took away the banc account information...

**Comment by SupercoopManresa** [comment]
easy_my_coop_website_portal/views/easy_my_coop_website_portal_templates.xml

https://github.com/SupercoopManresa/vertical-cooperative/commit/dd2c10af3e6ed6a02062266b5d5c74c5dd8d8f22

**Comment by robinkeunen** [comment]
This is not the best way to adapt the code to your own needs since you will need to constantly rebase your repo on ours to keep up to date.

I'd suggest either
- making a PR on our repository if you think that could benefit the other coop supermarkets
- making a custom module `mansera_custom` in your repository and, from there, overload the views from upstream.

I'm happy to schedule a call or point to documentation if you need assistance.

**Comment by SupercoopManresa** [comment]
Hi Robin (do you speak dutch?)
I am not a programmer althought I understand that I should put it as an separate module inside of easy my coop. If I have time I will see what I can do. For now I want odoo to be configured and to work (well it works, but I have still some problems to solve (and the barcode is a detail...))

We can talk if you like to and maybe you participate in april with de Coopdevs conference and we see eachother there?

sustainable greetings! Patrick

**Comment by robinkeunen** [comment]
Cool, let's meet in April then! 

I do not speak dutch, I'm from Liège (Luik) in Wallonia. :-)

**Comment by SupercoopManresa** [comment]
so If I would copy the "website-eater" and name it website-barcode and put my code in the views it would work or should I do more changes in other parts to have it funcioning as an new modul within Obeesdoo?

A final question. How do I turn off the automatic generated e-mails to request for capital?

**Comment by robinkeunen** [comment]
> so If I would copy the "website-eater" and name it website-barcode and put my code in the views it would work or should I do more changes in other parts to have it funcioning as an new modul within Obeesdoo?

It's a bit more complicated, you need to 

1. create a new module `website_eater_barcode` or `mansera_custom`
2. inherit from `easy_my_coop_website_portal `
3. create a view inheriting the view `website_portal_details_form`
4. add your xml at the correct location using an xpath element

The documentation is [here](https://www.odoo.com/documentation/12.0/reference/views.html#inheritance-specs)

> A final question. How do I turn off the automatic generated e-mails to request for capital?

Coopdevs has submitted a PR to allow email configuration at the company level, it's there and nearly ready: 
https://github.com/coopiteasy/vertical-cooperative/pull/146
