### ISSUE TITLE
no barcode genereated at the beescard

### ISSUE THREAD

**Issue by Patrickkappert** [beescoop/Obeesdoo#222]

**Comment by Patrickkappert** [comment]
Hello, after some problems all was solved exept that when I create the member card the barcode is not generated.
In what module is the wizard defined (to reload that module)

**Comment by robinkeunen** [comment]
Hi @Patrickkappert, this is something we have to cleanup. It is not working and the bees coop is using a solution outside of odoo :/

**Comment by Patrickkappert** [comment]
dont clean up because it works perfectly.. After reloading the base module we had to reestablish the permits to create the card.. That was all.. I put a barcode at the websitebportal and the members download an app of client cards and it works perfectly with s 2d barcode scanner of 25 euros that we use. You can close the issue, but don't clean up the code!

**Comment by robinkeunen** [comment]
Ok cool, that's a art of the code I don't know much :-)
