### ISSUE TITLE
translations in folder with wrong name

### ISSUE THREAD

**Issue by Patrickkappert** [beescoop/Obeesdoo#224]
Hello, it took me some time to find out that the name of the translation folder is wrong in beesdoo shift attendance.
(you  are using the module in english?).

Greetings,

**Comment by robinkeunen** [comment]
Thanks for spotting it, can you make a PR? Can you fix `website_portal_restrict_modification` too?

We're using the modules in english, french and dutch :-)

**Comment by robinkeunen** [comment]
@remytms fyi
