### ISSUE TITLE
cron send weekly emails (shift summary) miss one day

### ISSUE THREAD

**Issue by Yo-Be** [beescoop/Obeesdoo#231]
The selection is between now+1day and now+7days... to run weekly. So shifts that begins between now+7days and now+8days are never in the selection.

Workaround if there is a 24h period without shift, you can set the cron to match the blindspot to this period...
Or send it manually for the missing day.

https://github.com/beescoop/Obeesdoo/blob/f03a6bf02bd10afc9037133ac6545a8199efab72/beesdoo_shift/models/task.py#L324

Moreover, receiving the reminder 1 week in advance is quite early. Maybe a good idea would be an alternative daily in place of weekly that would select between now+(param)days and now+(param +1) days ...

**Comment by Patrickkappert** [comment]
we generated a shift for all the days of the week...

**Comment by vvrossem** [comment]
@Yo-Be fixed in #251 
Thank you for coming up with that solution :)
