### ISSUE TITLE
PR for additional translations?

### ISSUE THREAD

**Issue by yannp** [beescoop/Obeesdoo#234]
Hello, 

My name is Yann, I'm volunteering in the Som Alimentacio Supercoop in Valencia, Spain. We are starting to use your Odoo apps with the help of Coopdevs, just as SupercoopManresa. 

I just called @Patrickkappert of SupercoopManresa  because we are interested in their catalan translations of your apps. They created the .po files on their repo: https://github.com/SupercoopManresa/Obeesdoo. The translations are complete.

Since I understand that you are the maintainers of those apps, would you consider a PR to integrate additional translations to the repo? If you have another suggestion about how to manage this process we would be glad to hear it as we are really beginning our journey with Odoo.

Best regards

**Comment by robinkeunen** [comment]
Hi @yannp 

Yes! All PR are welcome, especially translations. Do you need assistance to submit the translations?

**Comment by yannp** [comment]
Great! In principle Patrick and I should be able to do the PR ourselves but I will let you know if we would need assistance.
