### ISSUE TITLE
Barcode and scale at pos

### ISSUE THREAD

**Issue by Patrickkappert** [beescoop/Obeesdoo#260]
We weight loose products at the scale at the pos. But we cannot assign a barcode to the product because it desactivates the scale and puts directly 1 kg to the weight. Is there a way to generate barcodes that not deactivate the scale?

**Comment by robinkeunen** [comment]
Hi there,

Did you check the barcode nomenclatures configuration ?  I think if you set it up as a scale product, it will try to read the product weight from the barcode.

If you read French, you can have a look at this doc: https://doc.it4socialeconomy.org I think coopdevs is translating it at the moment.
