### ISSUE TITLE
General project management - komunigi - 2 - technical axis

### ISSUE THREAD

**Issue by polchampion** [beescoop/Obeesdoo#262]
As of early 2022, axis 2 of the **komunigi** project is starting in earnest.

For context, see the overarching issues [RFC Moving Obeesdoo and Easy My Coop to OCA #247](https://github.com/beescoop/Obeesdoo/issues/247) and [RFC Moving Easy My Coop to OCA #170](https://github.com/coopiteasy/vertical-cooperative/issues/170).

The present issue encompasses project management tasks relating to the technical axis (2) of the komunigi project, ie to the two issues above.

Moving Obeesdoo and EMC to the OCA will require some project management tasks, notably :

- Organising and following the work module by module
- Organising regular sprints and follow-up
- Communicating about changes to users and publish regular release notes
- Maintaining and updating a public window to our progress within the technical axis

**Comment by robinkeunen** [comment]
Here are the 4 steps of the project as of 2022-02-01

# 1. Migrate vertical-cooperative

## 1.1 rename modules 

cf [Analysis - rename repositories and module #248](https://github.com/beescoop/Obeesdoo/issues/248)

**Depth 1**
- https://github.com/coopiteasy/vertical-cooperative/issues/203

**Depth 2**
- `easy_my_coop_be`
- `easy_my_coop_fr`
- `easy_my_coop_ch`
- `easy_my_coop_es`
- `easy_my_coop_es_website`
- `easy_my_coop_api`
- `easy_my_coop_api_logs`
- `easy_my_coop_website`
- `easy_my_coop_website_portal`
- `easy_my_coop_taxshelter_report`
- `easy_my_coop_loan`
- `easy_my_coop_dividend`
- `easy_my_coop_export_xlsx`
- `beesdoo_easy_my_coop`

**Depth 3**
- `easy_my_coop_connector`
- `easy_my_coop_website_taxshelter`
- `easy_my_coop_loan_website`
- `easy_my_coop_loan_account`
- `easy_my_coop_loan_bba`

**Depth 4**
- `easy_my_coop_loan_account_be`

![](https://user-images.githubusercontent.com/17589077/149750369-34ea7875-4afa-41dc-afa9-cb66113ba6bc.png)


## 1.2 rename models and xml_id suffixes

# Migrate Obeesdoo 

## 2.1 rename modules 

![](https://user-images.githubusercontent.com/17589077/149927982-58f1b329-9d15-48d3-b331-77741f7c2e87.png)
cf https://github.com/beescoop/Obeesdoo/issues/248

## 2.2 Rename models et xml_id suffixes

# 3. Technical refactoring 

- refacto already listed in odoo tasks
- todo and fixme scattered around the code

# 4. UX refactoring

- change of menu hierarchy
- change in form / tree views
- move configurations to better places
- analyse with users
