### ISSUE TITLE
Rename `beesdoo_easy_my_coop`

### ISSUE THREAD

**Issue by polchampion** [beescoop/Obeesdoo#276]
- [ ] ?

**Comment by polchampion** [comment]
@robinkeunen Not sure if this module must be included in the EMC work (or wait until we move to Obeesdoo modules) and what to do with it - it's not included in either diagram.

**Comment by polchampion** [comment]
[Note to self] Must create coopiteasy issues in order to link them to the project

**Comment by robinkeunen** [comment]
It should be included in obeesdoo's modules. The name in the diagram (had to look thrice) id `beesdoo_emc`

**Comment by victor-champonnois** [comment]
Cannot work on this until obeesdoo 12.0-komunigi is merged (because I need to be on top of both 12.0-komunigi and the refactorings on 12.0)
