### ISSUE TITLE
Split beesdoo_product into product_label_print_request

### ISSUE THREAD

**Issue by robinkeunen** [beescoop/Obeesdoo#403]
Contains some facilitation for label printing.

split beesdoo_product into product_label_print_request
or is it deprecated with new work to print labels (étiquettes) ? => check w/ analyst

**Comment by victor-champonnois** [comment]
According to virginie, it is still needed to use with Jasper (so for bees and spp)

**Comment by victor-champonnois** [comment]
-> à ajouter dans la description du module
