### ISSUE TITLE
Split beesdoo_product into product_note (oca/product-attribute)

### ISSUE THREAD

**Issue by robinkeunen** [beescoop/Obeesdoo#404]
Adds a 'Comments' field for use on labels.

**Comment by victor-champonnois** [comment]
This should be done after https://github.com/beescoop/Obeesdoo/issues/400

**Comment by victor-champonnois** [comment]
@robinkeunen I don't see the point of putting this in a separate module than beesdoo_product_label (https://github.com/beescoop/Obeesdoo/issues/400). I think it's better to think about this when we will merge with grap's product_label

**Comment by victor-champonnois** [comment]
@robinkeunen can I close this ?
