### ISSUE TITLE
split beesdoo_product into product_expiration and  product_sale_limit_date

### ISSUE THREAD

**Issue by robinkeunen** [beescoop/Obeesdoo#405]
Adds deadline for sale and consumption.
split beesdoo_product into product_expiration (deadline_for_consumption)
split beesdoo_product into product_sale_limit_date (deadline_for_sale)
=> check if used or whether it can be removed altogether
=> question the field name (expiration_date and sale_limit_date ?)

**Comment by victor-champonnois** [comment]
> check if used or whether it can be removed altogether 

Can you do that ? (along with what we discussed about [pos_unavailable_for_sale](https://github.com/beescoop/Obeesdoo/pull/466#issuecomment-1298591773) )

**Comment by robinkeunen** [comment]
I asked. Actually, I think everything in the tab "scale label" is only used at the bees with the bizerba scale. It could go into a custom module `product_scale_label`.

```xml
                <page
                    string="Scale labels"
                    attrs="{'invisible':[('to_weight','=',False)]}"
                >
                    <group>
                        <group name="scale_label">
                            <field name="deadline_for_sale" />
                            <field name="deadline_for_consumption" />
                            <field name="ingredients" />
                            <field name="scale_label_info_1" />
                            <field name="scale_label_info_2" />
                        </group>
                        <group>
                            <field name="scale_sale_unit" />
                            <field name="scale_category" widget="selection" />
                            <field name="scale_category_code" />
                        </group>
                    </group>
                </page>
```

Or even in a leftover beesdoo_label that would be migrated out in v16.

**Comment by victor-champonnois** [comment]
@robinkeunen OK, I'm going for splitting into `product_scale_label`
