### ISSUE TITLE
Split beesdoo_product into xxx_barcode

### ISSUE THREAD

**Issue by robinkeunen** [beescoop/Obeesdoo#408]
Generates barcodes.
add note to ROADMAP.rst : migrate to https://github.com/OCA/stock-logistics-barcode

**Comment by victor-champonnois** [comment]
@robinkeunen Should the name be `product_barcode` ? This name doesn't exist antwhere in OCA

**Comment by robinkeunen** [comment]
It seems too generic to me. `beesdoo_product` does not add barcode on products, it fills it. Maybe `product_barcode_generator`?

What do the others think ? @huguesdk @remytms

**Comment by victor-champonnois** [comment]
OK let's go for product_barcode_generator
