### ISSUE TITLE
Eater limit does not work

### ISSUE THREAD

**Issue by victor-champonnois** [beescoop/Obeesdoo#429]
@vdewulf test on lenid-test :

On tab "Eaters", I add a new Eater. I was able to create 3 eaters.I checked the config of "part sociale" and they may have 9 eaters. I tried to change this config but was not allowed because of user right issue:
Désolé, vous n'êtes pas autorisé à accéder à ce document. Seuls les utilisateurs avec les niveaux d'accès suivants sont actuellement autorisés à faire cela:

Administration/Settings
(Modèle de document: ir.config_parameter) - (Opération: read, Utilisateur : 1560)
==> Is it normal?

I added more than 10 Eaters and got no error validation.

**Comment by vdewulf** [comment]
I tested again today on lenid-test, and I got the error as expected when trying to add the 10th eater.
So this issue seems solved.
