### ISSUE TITLE
Cannot edit is_worker field in Contacts

### ISSUE THREAD

**Issue by ferdymercury** [beescoop/Obeesdoo#439]
Hello, thanks
I have two Odoo 12 instances in different servers, both having installed the EasyMyCoop and Beescoop Worker Status manager as well as shift management.

In one of the instances, I can freely select a partner from Contacts, and mark it as worker clicking on the checkbox."
In the second server, there seems to be a problem, as this checkbox is shown as read-only and I can not click on it, neither set it via API RPC.

![image](https://user-images.githubusercontent.com/10653970/180979618-2952b9ab-a53c-4ec3-8d65-92f8c17bb2c7.png)
--> Worker checkbox is frozen

Both WorkerStatus Manager modules are 12.0.1.0.0

I have checked that in both cases I have admin/settings rights, and I am a cooperative admin.

Any idea what I might be missing in one of the instances to be able to edit this field?

Or any idea on how to debug it via RPC?

Thanks in advance!

**Comment by robinkeunen** [comment]
Hi @ferdymercury 

Mmh, is_worker definition is a bit messy as it is overloaded in some places : 

First here : 
https://github.com/beescoop/Obeesdoo/blob/ca40cb0aab46cc27dfae236357f75281a35881d6/beesdoo_shift/models/res_partner.py#L15-L18

and here : 
https://github.com/beescoop/Obeesdoo/blob/ca40cb0aab46cc27dfae236357f75281a35881d6/beesdoo_easy_my_coop/models/res_partner.py#L13-L26

It is also in `macavrac_base` but I guess you don't use it.

The fist snippets makes `is_worker` writable and equivalent to `worker_store`. The second snippets overloads the field definition making it readonly=True (explicitly and also because computed without the _inverse_ function). The compute function uses worker_store though.

Not sure what happens on your side but maybe these considerations might help.

**Comment by ferdymercury** [comment]
Thanks for the swift reply!

In the server where it is not working, I started the database from scratch, so it is almost empty (no quotations, no purchase orders, and so on). Just added some contacts in res.partners. Could it be that there needs to be some more stuff elsewhere or company data defined for worker-store to correctly function?

**Comment by ferdymercury** [comment]
> The second snippets overloads the field definition making it readonly=True (explicitly and also because computed without the _inverse_ function).

I see that the second snippet was added only recently (5 months), so maybe that's why it works in the older server, but not in the new one?

I also see different fields (info session etc. though I do not know if that's rather something of the settings):

Old:
![image](https://user-images.githubusercontent.com/10653970/181042093-40361915-ccff-407d-b459-eac199e321d8.png)
--> No problem, I can click on "Worker"

New:
![image](https://user-images.githubusercontent.com/10653970/181041916-6b777ee3-e36b-4abe-85b3-63ad5d0d57db.png)
--> Problem, I can not click on "Worker"

**Comment by robinkeunen** [comment]
You can also have a look here : https://doc.it4socialeconomy.org

**Comment by ferdymercury** [comment]
We figured it out. It seems that the 'new' server has some additional modules installed than the older does not.

As a result, the Worker field being active is much more complicated than in the old one. In the new one, one has first to create a Share Type in the EMC module. In it, one has to select eater/worker, and click on Allow owner to work. Then, you go to the contact, and you create a subscription. Then you validate the invoice. Only then, the worker field becomes active.

I would like to keep this Issue open, and suggest the developers that they add a 'help message' if you hover over the worker checkbox, pointing at the solution.

**Comment by ferdymercury** [comment]
Just for the record, these modules were not installed in the old server, probably the beesdoo/coop link is the one creating the extra restrictions on the availability of the worker field.

![image](https://user-images.githubusercontent.com/10653970/181206234-5678c8bb-b784-4570-9e56-4b005f2d4e9d.png)

**Comment by robinkeunen** [comment]
Glad you found out what was happening. Do you have developers on hand to add the help message ?

**Comment by ferdymercury** [comment]
We don't, we are more user/level. I add though my suggestion below, to be added here (best guess):

https://github.com/beescoop/Obeesdoo/blob/86fed721147f762571137a8c5eeaa7d519c8989a/beesdoo_easy_my_coop/models/res_partner.py#L25

help = 'This field can only be set if Create Subscription button was clicked on this user and payment was validated, for a Share Type where Owner-can-work is checked'

**Comment by robinkeunen** [comment]
This will be added in quite some time because we're doing a big refactoring : the commit is here : https://github.com/beescoop/Obeesdoo/issues/439#issuecomment-1196477827

**Comment by ferdymercury** [comment]
Thanks a lot! Of course, no hurries.

Is this refactoring thought for odoo 12 or for later versions?

**Comment by robinkeunen** [comment]
For 12.0 already. It should be seamless for obeesdoo modules but for vertical-cooperative, you will need to run [this script](https://github.com/coopiteasy/vertical-cooperative/blob/12.0/rename_all_deprecated_modules.py) before running an update all on your database.

All this work is part of the [komunigi project](https://komunigi.org) which aims, among other things, to move all this code to the OCA.
