### ISSUE TITLE
Missing modules and dependencies

### ISSUE THREAD

**Issue by aborsu** [beescoop/Obeesdoo#93]
The dump that I have of the beescoop data contains a number of modules that should be installed but are not available or for which the install fails:
# Missing
* module l10n_be_vat_reports
* account_journal_report
* account_permanent_lock_move
* customer_activity_statement
* module customer_outstanding_statement
* website_portal_v10
* account_financial_report_qweb
# Cannot install
* module easy_my_coop_website_portal: Unmet dependencies: website_portal_v10
* module beesdoo_website_portal: Unmet dependencies: website_portal_extend
* module website_portal_extend: Unmet dependencies: website_portal_v10
* module beesdoo_website_eater: Unmet dependencies: website_portal_v10
* module easy_my_coop_website_taxshelter: Unmet dependencies: website_portal_v10
* module account_journal_lock_date: Unmet dependencies: account_permanent_lock_move

Does one of you know if this is normal or not? Is this something that some other doc contains?
Thanks,

**Comment by remytms** [comment]
Indeed, there is a missing repository:
https://github.com/OCA/website

This repo contains the `website_portal_v10` module.

Module `l10n_be_vat_reports` can be found in this branch of coopiteasy repo: https://github.com/coopiteasy/l10n-belgium/tree/9.0-mig-l10n_be_vat_reports
In the future, this branch will be merged with OCA repos, and therefore the reference to OCA repo will be enough.

Same idea for the `account_journal_report`, it's part of the account-financial-tools repo that is missing. And for now you should point to:
https://github.com/robinkeunen/account-financial-tools/tree/9.0-mig-account_journal_lock_date

And yet, this repo missing: 
https://github.com/OCA/account-financial-reporting

I have updated the readme accordingly. :)
