### ISSUE TITLE
Beesdoo_shift : missing dependency

### ISSUE THREAD

**Issue by vdewulf** [beescoop/Obeesdoo#97]
When I install on a fresh DB beesdoo_shift, the only depency is "beesdoo_base" (because we have some conditions about "worker_eater" on the res.partner.

However, I cannot work with this module in standalone, because it's impossible to subscribe a res.partner on a template shift on a planning week. This is because in the code, there are some references to the share type "a", related to business rules from BEES coop.

So we should either make the module completely independent, or simply state in the dependency that we need to install beesdoo_easy_my_coop - which creates the 3 types of shares A/B/C (and then alos easy my coop).

@tfrancoi @remytms what do you think?
Thanks for your input.

**Comment by tfrancoi** [comment]
There is the field cooperator_type in beesdoo base with the 3 type of share.
The only thing beesdoo_easy_my_coop do is to change the way the field is computed to be based on the share a partner actually buy.
So I don't see any issue here. If there is one, fixing it by setting beesdoo_easy_my_coop as dependency is not the right way

**Comment by vdewulf** [comment]
@tfrancoi The only problem with installing only beesdoo_shift it's that it is impossible to use the module. If there is no share assigned to the cooperator (and the only way to do it is by using easy my coop), there is no way to assign the person to a shift template nor shift.
So what would be the right thing to do?
The context of this request is that some cooperatives don't have the same shares as BEES coop (share a => work, share B/C => no work). Some have : share A/B => work, share B/C => no work.
I don't know if these potential customers will want to use the modules, but in this case, what would be the work to be done (and time estimate) to make it more generic?
Thanks!

**Comment by tfrancoi** [comment]
It's present in the view https://github.com/beescoop/Obeesdoo/blob/9.0/beesdoo_base/views/partner.xml#L23
you should be able to set the type of part manually on the res.partner. If it's not the case it should be fix in beesdoo_base.

**Comment by vdewulf** [comment]
@tfrancoi yes, correct, I managed to set a cooperator type on the database (without easy my coop installed). It's a bit strange but corresponds to the need we had.
Thanks! I think we can close this issue.
